### ISSUE TITLE
incomplete downloads

### ISSUE THREAD

**Issue by sgregori** [xates/tg-channel-watcher#4]
Hi,

Sometimes the downloads are incomplete when watching channels with video files.

Low speed download, but its not a problem, but a concurrent downloads limit will be interesting.

Great Job & Thank you very Much.

**Comment by xates** [comment]
Hi! :)

What do you mean with incomplete? That file doesn't download entirely? And _sometimes_?

The speed of the download depends on you internet connection and Telegram servers. 

You could try to increment the number of concurrent downloads by incrementing the parameter `update_workers` to have more update handlers working (downloading) concurrently.

**Comment by sgregori** [comment]
Sometimes, there are files that are not complete, for example, file that has 700 mb, it stops at 450 mb

However, reducing the number of threads or stacks to 1, this happens much less, and is OK.

Regarding speed, at home I have 300mb fiber, and telegram download very fast. And where I have the watcher, in a data center with gigabit connection, the speed was much lower, although a few days ago it seems to work much faster.

Thank you

**Comment by xates** [comment]
Try to install cryptg. It should drastically improve download (decoding, actually) speed and might resolve incomplete downloads too
